apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fedora-db
  namespace: usefedora
  description: The main database for Fedora
  annotations:
    github.com/project-slug: UseFedora/fedora
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  lifecycle: production
  system: fedora
  owner: group:usefedora/everyone
  dependencyOf:
    - resource:usefedora/fedora