apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fedora
  namespace: usefedora
  description: The main Rails application for Teachable
  annotations:
    github.com/project-slug: UseFedora/fedora
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  system: system:usefedora/fedora
  owner: group:usefedora/everyone
  dependsOn:
    - component:usefedora/mono-frontend
    - component:usefedora/fedora-redis
    - component:usefedora/fedora-postgres