apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mono-frontend
  namespace: usefedora
  description: The frontend for the Fedora Repository
  annotations:
    github.com/project-slug: UseFedora/mono-frontend
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: usefedora/engineers
  system: system:usefedora/fedora
  dependsOn:
    - component:usefedora/fedora
    - component:usefedora/fedora-redis
    - component:usefedora/fedora-postgres